version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "hello-world.bargeacbl.com"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - cd hello-world
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started 
            - ng build
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed 
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes